package poly.qlchsach.ui;

import Poly.qlchsach.helper.MessageDialogHelper;
import Poly.qlchsach.helper.ShareHelper;
import Poly.qlchsach.ui.ChaoJDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;

public class MainJFrame extends javax.swing.JFrame {

    private QLHoaDon hoaDonPanel;
    private QLKhachHangJPanel khachHangPanel;
    private QLNhanVienJPanel nhanVienPanel;
    private QLSachJPanel sachPanel;
    private QLTaiKhoan taiKhoanPanel;
    private ThongKeDoanhThuJPanel thongKePanel;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();

        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);;
        init();
    }

    void init() {
        setSize(1000, 600);
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss aa");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(format.format(new Date()));
            }
        }).start();
        this.welcome();
        this.openLogin();
    }

    void welcome() {
        new ChaoJDialog(this, true).setVisible(true);
    }
    void openLogin() {
        new DangNhapJDialog(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnQLS = new javax.swing.JButton();
        btnQLNV = new javax.swing.JButton();
        btnQLKH = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnGioithieu = new javax.swing.JButton();
        pnlMain = new javax.swing.JTabbedPane();
        txtMain = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniChangePassWord = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniQLHD = new javax.swing.JMenuItem();
        mniQLKH = new javax.swing.JMenuItem();
        mniQLNV = new javax.swing.JMenuItem();
        mniQLS = new javax.swing.JMenuItem();
        mniQLTK = new javax.swing.JMenuItem();
        mnuThongke = new javax.swing.JMenu();
        mnithongKeDoanhThu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.add(jSeparator1);

        btnQLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/qlsach.jpg"))); // NOI18N
        btnQLS.setText("QL SÁCH");
        btnQLS.setFocusable(false);
        btnQLS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLS);

        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/qlkh.png"))); // NOI18N
        btnQLNV.setText("QL NHÂN VIÊN");
        btnQLNV.setFocusable(false);
        btnQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLNV);

        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/User group.png"))); // NOI18N
        btnQLKH.setText("QL KHÁCH HÀNG");
        btnQLKH.setFocusable(false);
        btnQLKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLKH);
        jToolBar1.add(jSeparator2);

        btnGioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Label.png"))); // NOI18N
        btnGioithieu.setText("Giới Thiệu");
        btnGioithieu.setFocusable(false);
        btnGioithieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioithieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioithieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioithieu);

        pnlMain.setName("tab1"); // NOI18N
        pnlMain.setRequestFocusEnabled(false);
        pnlMain.addTab("Home", txtMain);

        jLabel2.setText("Nhóm 1");

        lblDongHo.setText("8:00 pm");

        jMenu1.setText("Hệ thống");

        mniLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Key.png"))); // NOI18N
        mniLogin.setText("Đăng Nhập");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogin);

        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Exit.png"))); // NOI18N
        mniLogout.setText("Đăng Xuất");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogout);

        mniChangePassWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Refresh.png"))); // NOI18N
        mniChangePassWord.setText("Đổi Mật Khẩu");
        mniChangePassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePassWordActionPerformed(evt);
            }
        });
        jMenu1.add(mniChangePassWord);

        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Stop.png"))); // NOI18N
        mniExit.setText("Kết Thúc");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        jMenu1.add(mniExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mniQLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Price list.png"))); // NOI18N
        mniQLHD.setText("Quản Lý Hóa Đơn");
        mniQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLHDActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLHD);

        mniQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/User group.png"))); // NOI18N
        mniQLKH.setText("Quản Lý Khách Hàng");
        mniQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLKHActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLKH);

        mniQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/qlkh.png"))); // NOI18N
        mniQLNV.setText("Quản Lý Nhân Viên");
        mniQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNVActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLNV);

        mniQLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/qlsach.jpg"))); // NOI18N
        mniQLS.setText("Quản Lý Sách");
        mniQLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLS);

        mniQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/qltk.jpg"))); // NOI18N
        mniQLTK.setText("Quản Lý Tài Khoản");
        mniQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLTKActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLTK);

        jMenuBar1.add(jMenu2);

        mnuThongke.setText("Thống kê");
        mnuThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThongkeActionPerformed(evt);
            }
        });

        mnithongKeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Poly/qlchsach/icons/Dollar.png"))); // NOI18N
        mnithongKeDoanhThu.setText("Thống kê doanh thu theo năm");
        mnithongKeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnithongKeDoanhThuActionPerformed(evt);
            }
        });
        mnuThongke.add(mnithongKeDoanhThu);

        jMenuBar1.add(mnuThongke);

        jMenu6.setText("Trợ giúp");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(pnlMain)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDongHo))
                .addContainerGap())
        );

        pnlMain.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSActionPerformed
        // TODO add your handling code here:
        mniQLSActionPerformed(evt);
    }//GEN-LAST:event_btnQLSActionPerformed

    private void mniQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLHDActionPerformed
        // TODO add your handling code here:
        if(ShareHelper.isLogin()){
            if (hoaDonPanel == null) {
            hoaDonPanel = new QLHoaDon();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            pnlMain.addTab("Quản Lý Hóa Đơn", icon, hoaDonPanel, "Quản Lý Hóa Đơn");
        }
        pnlMain.setSelectedComponent(hoaDonPanel);
        } else {
            MessageDialogHelper.showMessageDialog(this, "Vui lòng đăng nhập", "Thông báo");
        }
    }//GEN-LAST:event_mniQLHDActionPerformed

    private void mniQLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSActionPerformed
        // TODO add your handling code here:
        if(ShareHelper.isLogin()){
            if (sachPanel == null) {
            sachPanel = new QLSachJPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            pnlMain.addTab("Quản Lý Sách", icon, sachPanel, "Quản Lý Sách");
        }
        pnlMain.setSelectedComponent(sachPanel);
        } else {
            MessageDialogHelper.showMessageDialog(this, "Vui lòng đăng nhập", "Thông báo");
        }
    }//GEN-LAST:event_mniQLSActionPerformed

    private void mniChangePassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePassWordActionPerformed
        // TODO add your handling code here:
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniChangePassWordActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        // TODO add your handling code here:
        mniQLNVActionPerformed(evt);
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void mniQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLKHActionPerformed
        // TODO add your handling code here:
        if(ShareHelper.isLogin()) {
            if (khachHangPanel == null) {
            khachHangPanel = new QLKhachHangJPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            pnlMain.addTab("Quản Lý Khách Hàng", icon, khachHangPanel, "Quản Lý Khách Hàng");
        }
        pnlMain.setSelectedComponent(khachHangPanel);
        } else {
            MessageDialogHelper.showMessageDialog(this, "Vui lòng đăng nhập", "Thông báo");
        }
    }//GEN-LAST:event_mniQLKHActionPerformed

    private void mniQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNVActionPerformed
        // TODO add your handling code here:
        if(ShareHelper.isLogin()) {
            if (nhanVienPanel == null) {
            nhanVienPanel = new QLNhanVienJPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            pnlMain.addTab("Quản Lý Nhân Viên", icon, nhanVienPanel, "Quản Lý Nhân Viên");
        }
        pnlMain.setSelectedComponent(nhanVienPanel);
        } else {
            MessageDialogHelper.showMessageDialog(this, "Vui lòng đăng nhập", "Thông báo");
        }
    }//GEN-LAST:event_mniQLNVActionPerformed

    private void mniQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLTKActionPerformed
        // TODO add your handling code here:
        if(ShareHelper.isManager()) {
            if (taiKhoanPanel == null) {
            taiKhoanPanel = new QLTaiKhoan();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            pnlMain.addTab("Quản Lý Tài Khoản", icon, taiKhoanPanel, "Quản Lý Tài Khoản");
        }
        pnlMain.setSelectedComponent(taiKhoanPanel);
        } else {
            MessageDialogHelper.showMessageDialog(this, "Bạn không có quyền truy cập chức năng này", "Thông báo");
        }
    }//GEN-LAST:event_mniQLTKActionPerformed

    private void btnQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKHActionPerformed
        // TODO add your handling code here:
        mniQLKHActionPerformed(evt);
    }//GEN-LAST:event_btnQLKHActionPerformed

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        // TODO add your handling code here:
        new DangNhapJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mnuThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThongkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuThongkeActionPerformed

    private void mnithongKeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnithongKeDoanhThuActionPerformed
        // TODO add your handling code here:
        if(ShareHelper.isManager()){
            if (thongKePanel == null) {
            thongKePanel = new ThongKeDoanhThuJPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            pnlMain.addTab("Thống kê", icon, thongKePanel, "Thống kê");
        }
        pnlMain.setSelectedComponent(thongKePanel);
        } else {
            MessageDialogHelper.showMessageDialog(this, "Bạn không có quyền truy cập chức năng này", "Thông báo");
        }
    }//GEN-LAST:event_mnithongKeDoanhThuActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
        openLogin();
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void btnGioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioithieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGioithieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGioithieu;
    private javax.swing.JButton btnQLKH;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniChangePassWord;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniQLHD;
    private javax.swing.JMenuItem mniQLKH;
    private javax.swing.JMenuItem mniQLNV;
    private javax.swing.JMenuItem mniQLS;
    private javax.swing.JMenuItem mniQLTK;
    private javax.swing.JMenuItem mnithongKeDoanhThu;
    private javax.swing.JMenu mnuThongke;
    private javax.swing.JTabbedPane pnlMain;
    private javax.swing.JLabel txtMain;
    // End of variables declaration//GEN-END:variables
}
